# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RA Map
email: Parton-A1@email.ulster.ac.uk
description: Welcome to RA Map - a graphical representation of rheumatoid arthritis at a cellular level (REWRITE)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: andrewsparton
github_username:  aparton

# Build settings
markdown: kramdown
